#!/bin/bash
#Installs tmux, htop, glances, netstat and iftop (debian based systems only) and starts a custom 4-pane session
#to remove the password requirement for iftop and netstat
#first type
#  which iftop netstat
#to get the locations of iftop and netstat
#  type sudo visudo and hit ENTER, then add the line (without the #)
#your username here	ALL=(ALL) NOPASSWD:full path to iftop here,path to netstat here
#example
#bill	ALL=(ALL) NOPASSWD:/usr/sbin/iftop,/bin/netstat
#then reboot for changes to take effect
#
#defaults to 4-pane session, can also open 2-pane session with log watcher and master window

ponies='while true; do clear; (fortune | ponysay); read -sn 1 -t 8 dummy; done' # everypony loves a pony

doInstall () {
 if which apt; then
   if (sudo apt install "$1"); then
     return 0
   else
     return 1
   fi
 elif which pacman; then
   if (sudo pacman -Syu "$1"); then
     return 0
   else
     return 1
   fi
 fi
}

doFail () {
  echo "Failed. You need to install the $1 package yourself, sorry. Exiting"
  exit $2	
}

for a in tmux fortune ponysay lolcat glances htop iftop netstat; do
  if ! (which $a > /dev/null); then
    echo "Installing $a..."
    if ! (doInstall $a); then
      doFail "$a" 1
    fi
  fi
done

if ! (which watchlogtails > /dev/null); then
  fldr=$(dirname $0)
  echo "Getting viewlogtails and watchlogtails from github"
  pushd "$fldr" > /dev/null
  for a in viewlogtails watchlogtails; do
    wget -q "https://github.com/hp6000x/watchlogtails/raw/master/$a"
    chmod a+x $a
  done
  popd > /dev/null
fi

if [[ -z "$1" ]] || [[ "$1" = "4" ]] || [[ "$1" = "-g" ]]; then #default to 4-pane
  if [[ "$1" = "4" ]]; then
    shift
  fi

  if ! (tmux attach -t 4pane > /dev/null); then
    tmux new-session -d -s 4pane

    tmux set -g mouse on

    tmux split-window -h -t 0
    tmux split-window -v -t 0
    tmux split-window -v -b -p 25 -t 2
    if [[ "$1" = "-g" ]]; then
      tmux send-keys -t 0 "glances; exit" Enter
    else
      tmux send-keys -t 0 "htop; exit" Enter
    fi
    tmux send-keys -t 1 "sudo iftop -o 40s; exit" Enter
    tmux send-keys -t 2 "dmesg --follow; exit" Enter
    tmux send-keys -t 3 "watch -n 5 sudo netstat --inet -ap; exit" Enter
    tmux select-pane -t 3
    tmux attach -t 4pane
  fi

elif [[ "$1" = "2" ]]; then #2-pane chosen

  if ! (tmux attach -t 2pane > /dev/null); then
    tmux new-session -d -s 2pane
    tmux set -g mouse on
    tmux split-window -h -p 50 -t 0
    tmux split-window -h -p 70 -t 0
    tmux send-keys -t 2 "exit" Enter
    tmux send-keys -t 0 "watchlogtails; exit" Enter
    tmux send-keys -t 1 "$ponies" Enter
    tmux select-pane -t 1
    tmux attach -t 2pane
  fi

else

  echo "Format is:-"
  echo "	$0 [4] [-g]	: Open 4-pane tmux session. -g chooses glances instead of htop"
  echo "	$0 2		: Open 2-pane tmux session"
  
fi 
